// SPDX-License-Identifier: MIT
//
// Two hulls that can strike each other.
//
// Everything downstream of an impact exists -- a structural mesh, buckling, a
// solid-shell element, and failed panels that become flooding openings whose rate
// follows the orifice law. Everything upstream exists too -- a 6-DOF rigid body
// with hydrostatics, radiation, propulsion and steering in a real seaway. This
// file is the middle: it answers *whether* two hulls are interfering, *where* and
// *how much*, and turns that into a force on both of them.
//
// It is the rigid-body half only. There is no fracture and no deformation here;
// what a rigid contact gets wrong because of that is stated in §5.
//
// --- 1. Detection: a penetration volume, not a list of contact points ----------
//
// The usual game-physics answer is a manifold of contact points, each with a
// normal and a depth, generated by clipping one convex piece against another. It
// is the wrong answer here for three reasons:
//
//   * **A ship hull is not convex** and its convex decomposition is not obvious.
//     Bulbous bow, transom tuck, the flare above the knuckle -- every one of them
//     is a concavity, and a decomposition that gets one wrong invents contact
//     where there is none.
//   * **The point count is a tessellation artefact.** Two hulls meeting over the
//     same square metre produce four contacts or forty depending only on how
//     finely the shell was wound, and a penalty force summed over them scales
//     with that count. The force then depends on the mesh rather than on the ship.
//   * **The structural model downstream wants a patch, not a point.** `breach.hpp`
//     asks which panels failed; `scantlings.hpp` describes plating by strake and
//     frame bay. "42 MN over 18 m2 centred here" is a load case. "Nine points with
//     depths" is not.
//
// So detection computes the **interpenetration solid** A ∩ B: its volume, its
// centroid, its principal extents, and the two surface patches that bound it. The
// engine already integrates closed meshes exactly, and that is what is exploited.
//
// **How.** A closed, outward-wound mesh satisfies, for any apex `o`,
//
//     1_B(x) = Σ_j sign_j · 1_{tet_j}(x),   tet_j = (o, a_j, b_j, c_j)
//
// pointwise almost everywhere -- this is the same signed-cone identity that makes
// `integrate()` correct for any apex, stated for the indicator rather than for the
// volume. It turns "is this point inside a general closed mesh" into a sum over
// *convex* pieces, and a tetrahedron is an intersection of four half-spaces, which
// is the one thing this engine's geometry is built to clip against.
//
// Applied to a triangle T of ∂A, it gives area(T ∩ B) = Σ_j sign_j area(T ∩ tet_j),
// and each term is a convex polygon clip -- no welding, no cap stitching, no
// ear clipping, no mesh boolean. Summing the divergence-theorem flux of those
// polygons over ∂A ∩ B and ∂B ∩ A gives the volume, centroid and second moments
// of A ∩ B **exactly**, because ∂(A ∩ B) is precisely those two pieces. The same
// sweep yields each patch's area, centroid and area-weighted normal for free,
// which is the whole answer the structure wants.
//
// The cost is O(triangles of A × triangles of B), so both meshes are first cut
// down to the overlap region with `clipToBox` -- valid because A ∩ B ⊆ box implies
// A ∩ B = (A ∩ box) ∩ (B ∩ box) -- and the box is tightened a couple of times
// against the clipped meshes' own bounds. The box is then padded outward, which
// costs nothing and buys something worth having: A ∩ B is then *strictly* inside
// it, so the cut faces `clipToBox` introduces lie outside the overlap and
// contribute exactly zero to both the volume and the patch areas. No provenance
// tracking is needed to keep the box's own caps out of the reported contact patch.
//
// --- 2. Depth and patch, from the overlap's own second moments ------------------
//
// A penetration volume alone does not say how deep. The second moments do: a
// uniform box of side lengths (d1, d2, d3) has covariance eigenvalues d_i^2 / 12,
// so the eigen-decomposition of the overlap's covariance gives an **equivalent
// box** whose dimensions are recovered exactly for a box and sensibly for anything
// lens-shaped. The smallest extent is the penetration depth; volume divided by it
// is the projected patch area; the corresponding eigenvector is a contact normal
// that owes nothing to any tessellation.
//
// The normal actually reported is the better-conditioned one: the area-weighted
// mean of the *surface* normals over the two patches, `normalize(mB - mA)`, which
// for a bow entering a flat side is exactly the side's own normal. The principal
// axis is kept as a cross-check and as the fallback when the patches degenerate.
// `normalAgreement` -- how nearly antiparallel the two patches' mean normals are
// -- is published rather than consumed, because it is the number that says whether
// "one contact patch" was a fair description of what the geometry actually did.
//
// --- 3. Response: a compliant force, not an impulse -----------------------------
//
// At 6 m/s closing, two 20,000 t ships are **not** an impulsive problem. Take a
// contact stiffness that puts the peak force where ship-collision measurements put
// it and the contact half-period is sqrt(m_red/K)·π ≈ 0.5 s -- fifty to a hundred
// simulation steps. An impulse would collapse all of that into one step and hand
// the structural model a velocity change, when what it needs is a force history: a
// rise time, a peak, a patch that grows and moves, and an energy that accumulates.
// So the primary model is a **penalty** contact:
//
//     F = stiffness · volume · (1 + dissipation · approachRate),   clamped >= 0
//
// Force proportional to the overlap *volume* rather than to a depth is the
// hydroelastic form, and it is the one that is mesh-independent: it has no contact
// count in it, it is continuous as the patch grows, and `stiffness` is an honest
// physical quantity (a contact pressure per metre of penetration, Pa/m). The
// dissipation term is Hunt-Crossley -- proportional to the penetration -- so the
// force is zero at first touch and at separation and never goes tensile, which a
// linear dashpot does at both ends.
//
// The impulsive solver is still here, `normalImpulse()`, for three reasons: it is
// the closed form the penalty model's conservation is checked against, it is the
// right model for a low-speed nudge that would otherwise be resolved in one step,
// and its energy figure `(1 - e^2)/2 · m_eff · u^2` is the *target* the penalty
// force's work integral has to reach. Both apply equal and opposite loads at one
// shared point, so both conserve linear and angular momentum identically.
//
// --- 4. Nothing here replaces a lumped stand-in ---------------------------------
//
// Three times in `ship.cpp` -- radiation, Ikeda, the MMG polynomial -- coupling a
// real model in has meant *deleting* a fraction-of-critical damper that was
// secretly doing the same job, because adding the real thing alongside its own
// stand-in damps the ship twice. Contact does **not** have that problem, and it is
// worth saying why rather than leaving it to be rediscovered.
//
// Every damping, added-mass and drag term in `integrateRigidBody()` is a *fluid*
// mechanism: radiation, viscous roll, cross-flow drag, hull resistance. All of
// them act on a ship that is nowhere near another ship, none of them was ever a
// proxy for hull-to-hull contact, and none of them switches off while contact is
// happening. So `Ship` loses nothing when this arrives; it gains an external force
// accumulator and that is all.
//
// The one double count that *does* exist is small and in the other direction:
// while the hulls overlap, both ships claim buoyancy from the same displaced
// water. A ram deep enough to matter -- 10 m3 of overlap -- credits 10 t of extra
// buoyancy against 20,000 t of ship, so it is below the noise of everything else,
// and removing it would mean subtracting the overlap from each hull's own
// hydrostatic integral, which is a real cost for no observable change.
//
// --- 5. What this cannot represent ----------------------------------------------
//
//   * **Two contact regions at once.** A bow and a quarter touching simultaneously
//     produce one volume, one centroid and one force, applied *between* them,
//     where nothing is touching. The volume is right and the moment is wrong. This
//     is the one thing a contact-point list does better, and `normalAgreement`
//     and `patchSeparation` are published precisely so the case announces itself
//     instead of quietly delivering a plausible wrong yaw: two regions a ship's
//     length apart put the two patch centroids a ship's length apart, where a
//     single region puts them within its own penetration depth.
//   * **Deep or engulfing penetration.** Once the overlap stops being a thin lens
//     -- past roughly a third of the striking bow's own width -- the equivalent
//     box is no longer flat and the "smallest extent" stops being a depth. In a
//     real ship that state is reached long after the shell has failed, which is a
//     different stream's problem, but nothing here detects it for you.
//   * **The structure.** The contact is rigid. A real 6 m/s ram spends most of its
//     energy crushing bow and side, at roughly constant force over metres of
//     penetration; a rigid contact instead reaches a much higher peak force over a
//     much smaller penetration, for the same absorbed energy. Peak force is
//     therefore an *over*-estimate and penetration an *under*-estimate, and only
//     the energy and the patch location survive the approximation intact.
//   * **Hydrodynamic interaction.** The water squeezed out from between two
//     closing hulls resists, and the added mass of a hull alongside another is not
//     the added mass of a hull alone. Neither is modelled; both make a real
//     collision slightly softer than this one.
//   * **Coincident surfaces** are handled, but by a convention rather than by
//     physics, and only the aligned half of the convention is exact. Where a face
//     of one hull lies exactly in a face of the other with the *same* outward
//     direction, that face bounds the overlap once and each sweep contributes half
//     of it -- exact, and the fix for a 5/3 volume error two flush boxes used to
//     produce. Where the normals *oppose*, the hulls are touching from outside and
//     the face contributes nothing -- exact whenever the coincident tetrahedron is
//     the only one claiming it, which covers two convex hulls laid flush, and not
//     otherwise: a face on a non-convex solid's own skin can also be claimed by a
//     tetrahedron it is not coplanar with. Deciding membership per point on a
//     coincident face is the coincident-face problem every mesh boolean has and it
//     is not solved here, so that case is **reported in `problems`** rather than
//     guessed at. It needs exact coplanarity -- to a part in 1e9 of the contact
//     region -- which two independently placed hulls do not produce. The reported
//     patch areas also split an aligned shared face evenly between the two hulls,
//     which is a choice and not a measurement.
//
// SI throughout; world frame unless a name says `Body`.
#pragma once

#include "ship.hpp"

#include <array>

namespace sim {

// --- Moments of a closed mesh ------------------------------------------------

// Volume and the first two moments of a solid, taken about a stated reference
// point. Held about a reference rather than about the centroid because moments
// about a common point are *additive*, which is what lets an overlap solid be
// accumulated out of signed pieces.
struct SolidMoments {
    double volume = 0;       // m^3
    Vec3   first{};          // m^4, integral of (x - reference)
    // Spelled `= Mat3::zero()` rather than `{}` on purpose: Mat3's default member
    // initialiser is the *identity*, so a value-initialised one is I, not 0.
    Mat3   second = Mat3::zero();  // m^5, integral of (x-ref) (x) (x-ref)
    Vec3   reference{};      // m, the point the moments are taken about

    Vec3 centroid() const;
    // Second moment about the centroid, divided by volume: the covariance of a
    // uniform solid. Independent of `reference`, which is why it is the thing
    // shape is read out of.
    Mat3 covariance() const;
};

SolidMoments solidMoments(const TriMesh& mesh, const Vec3& reference = {});

// The uniform box with the same volume, centroid and covariance as a solid.
// Recovered exactly for a box; for anything lens-shaped the smallest extent is a
// thickness and the other two span the patch.
struct PrincipalBox {
    Vec3 centre{};
    std::array<Vec3, 3>  axis{};    // unit, right-handed, ordered with extent
    std::array<double, 3> extent{}; // m, descending
};
PrincipalBox principalBox(const SolidMoments& moments);

// Eigen-decomposition of a symmetric 3x3 by cyclic Jacobi. Eigenvalues descending;
// `vectors[i]` is the unit eigenvector of `values[i]`.
void symmetricEigen(const Mat3& a, std::array<double, 3>& values,
                    std::array<Vec3, 3>& vectors);

// --- Detection ----------------------------------------------------------------

// One hull's share of the contact: the part of its own surface that is inside the
// other hull.
struct ContactPatch {
    double area = 0;        // m^2 of this hull's shell inside the other
    Vec3   centroid{};      // world, area-weighted
    Vec3   normal{};        // world unit, area-weighted outward normal of this hull

    // The same two in this ship's body frame. Filled only by shipContact() and
    // applyContact(), which are the calls that know what a body frame is; left at
    // zero by hullContact(), which is handed world meshes and nothing else.
    Vec3   centroidBody{};
    Vec3   normalBody{};
};

struct HullContact {
    bool   touching = false;
    double volume = 0;         // m^3 of interpenetration
    Vec3   centroid{};         // world, centroid of the overlap solid
    Vec3   normal{};           // world unit, out of B into A: push A along +normal
    double depth = 0;          // m, the overlap's smallest principal extent
    double patchArea = 0;      // m^2, volume / depth -- the projected contact patch
    Vec3   extent{};           // m, the overlap's principal extents, descending

    ContactPatch onA, onB;

    // Diagnostics that say whether "one contact patch" described what happened.
    // -1 would be the two surfaces facing the same way, which is nonsense; +1 is a
    // clean opposed contact. Below about 0.5, read §5.
    double normalAgreement = 0;
    // Distance between the two patch centroids, m. Comparable to `depth` for a
    // single contact region; comparable to a ship length for two of them.
    double patchSeparation = 0;

    // Complaints about the geometry rather than about the contact: a hull that is
    // not a closed manifold, a box clip that produced one. Advisory, in the spirit
    // of Ship::validate().
    std::vector<std::string> problems;
};

struct ContactParams {
    // Overlaps below this are not contact. A cubic millimetre of hull is a
    // rounding artefact of two meshes grazing, not a collision.
    double minVolume = 1e-6;      // m^3

    // How many times to re-cut the overlap box against the clipped meshes' own
    // bounds. Each round costs two box clips and pays for itself many times over
    // in the O(n*m) polygon sweep that follows; past two or three it stops moving.
    int    boxRounds = 3;

    // Outward pad on the overlap box, as a fraction of its diagonal plus an
    // absolute floor. Its only job is to keep A ∩ B strictly inside the box so the
    // box's own cut faces contribute nothing -- see §1.
    double boxPadFraction = 0.02;
    double boxPadFloor = 0.05;    // m

    // Check the box-clipped meshes are still closed manifolds and fall back to the
    // unclipped hull if not. Cheap on a clipped chunk, and the alternative to
    // noticing is an exactly-plausible wrong volume.
    bool   verifyClips = true;
};

// The interpenetration of two closed hulls, both already in world coordinates.
HullContact hullContact(const TriMesh& worldA, const TriMesh& worldB,
                        const ContactParams& params = {});

// The same for two ships, transforming each hull out of its body frame and filling
// in the body-frame patch fields. `a` is the body the normal points *towards*.
HullContact shipContact(const Ship& a, const Ship& b, const ContactParams& params = {});

// --- Response -----------------------------------------------------------------

// A rigid body as the contact solver sees it. Deliberately not a Ship: the
// conservation laws this has to satisfy are properties of six numbers and a
// tensor, and testing them against a ship would mean testing them through
// buoyancy, drag and a wave field.
//
// **Whether `mass` and `inertia` include entrained water is the caller's
// decision, and it changes what is conserved.** With the bare rigid mass, the two
// bodies conserve momentum between themselves exactly. With added mass folded in,
// each body accelerates less, and the missing momentum is in the water -- which is
// physically right and numerically means the pair's momentum is no longer the
// conserved quantity. `applyContact()` below goes through Ship, which divides by
// the effective mass including added mass, and therefore takes the second horn.
struct ContactBody {
    double mass = 0;           // kg
    // Zero, not `{}`: Mat3's default member initialiser is the identity, and a
    // default-constructed body is meant to be the *immovable* one -- zero mass and
    // a singular inertia, whose reciprocals are both the infinite limit.
    Mat3   inertia = Mat3::zero();  // kg m^2 about the cog, WORLD axes
    Vec3   cog{};              // world
    Vec3   velocity{};         // world, of the centre of gravity
    Vec3   angularVelocity{};  // world, rad/s

    Vec3   velocityAt(const Vec3& worldPoint) const;
    double kineticEnergy() const;
    Vec3   momentum() const;
    Vec3   angularMomentum(const Vec3& about) const;
};

struct ImpulseSolution {
    Vec3   impulse{};          // N s along the normal, applied to A; -this to B
    double effectiveMass = 0;  // kg, the reduced mass of the pair at this contact
    double approachSpeed = 0;  // m/s, positive when the two are closing
    double energyLost = 0;     // J, exactly (1 - e^2)/2 * effectiveMass * approach^2
};

// The frictionless normal impulse that gives the pair a separation speed of
// `restitution` times their approach speed. Computes only; `applyImpulse` applies.
// Split so a test can check the closed form against the state it was derived from.
ImpulseSolution normalImpulse(const ContactBody& a, const ContactBody& b,
                              const Vec3& point, const Vec3& normal, double restitution);

// Apply `impulse` to A and -`impulse` to B, both at `point`. One shared point is
// what makes angular momentum conserved about every origin, not just about the
// system centre of mass.
void applyImpulse(ContactBody& a, ContactBody& b, const Vec3& point, const Vec3& impulse);

struct ContactMaterial {
    // Contact pressure per metre of penetration, Pa/m: the normal force is
    // `stiffness * overlapVolume`.
    //
    // The default puts a 20 m2 patch at 0.3 m penetration on 120 MN, which is
    // where measured ship-collision load-penetration curves sit, and gives two
    // 20,000 t ships a contact half-period near half a second -- fifty steps at
    // dt = 0.01, so the force history is resolved rather than impulsive. Raising
    // it stiffens the contact and shortens it; the explicit integrator needs
    // dt < 2 sqrt(m_reduced / (stiffness * patchArea)).
    double stiffness = 2e7;       // Pa/m

    // Hunt-Crossley dissipation, s/m.
    //
    // Its small-dissipation law is e = 1 - (2/3) * dissipation * approachSpeed,
    // and that law is only asymptotic: **measured** on the flat-block fixture at
    // 6 m/s, the slope is 3.92 against the predicted 4.00 at 0.005 s/m and has
    // fallen to 2.05 by 0.25 s/m, where the linear extrapolation would have said
    // e = 0 and the truth is e = 0.49. Reading the first-order formula as a
    // calibration rather than as a limit is how a default gets chosen twice as
    // elastic as intended, which is exactly what happened here.
    //
    // So the default is measured, not extrapolated: 0.8 s/m delivers e = 0.20 at
    // 6 m/s and absorbs 96% of the closing energy, which is where ship-collision
    // energy ratios sit. It is speed dependent by construction -- 0.65 at 1 m/s,
    // 0.12 at 10 m/s -- and that is the right direction, since a gentle touch does
    // less plastic damage than a ram. It carries the whole burden of energy
    // absorption because the crushing that really does the work is not here.
    double dissipation = 0.8;     // s/m

    // Coulomb friction between the two shells, regularised over `frictionSpeed` so
    // the tangential force is continuous through a reversal instead of chattering.
    // Steel on steel, wet, is 0.2-0.4.
    double friction = 0.3;
    double frictionSpeed = 0.05;  // m/s
};

struct ContactLoad {
    Vec3   force{};          // N on A; -force on B, at the same point
    Vec3   point{};          // world, where it acts on both
    double normalForce = 0;  // N along the contact normal
    double pressure = 0;     // Pa, normalForce / patchArea
    double approachRate = 0; // m/s, positive while closing
    Vec3   slip{};           // m/s, tangential relative velocity of A over B
};

// The compliant contact force for one step. Zero force -- not a negative one --
// when the bodies are separating faster than the spring can follow.
ContactLoad contactLoad(const HullContact& contact, const ContactBody& a,
                        const ContactBody& b, const ContactMaterial& material);

// The running account of one contact event: what the structural model is handed
// when the collision is over.
struct ContactHistory {
    double duration = 0;      // s in contact
    // J taken out of the two bodies' kinetic energy. A rectangle rule on the
    // contact power evaluated at the *start* of each step, so it is **first order
    // in dt** -- measured at 1.5% of the closing energy at dt = 1 ms and halving
    // exactly with the step. That is a diagnostic accuracy, not a force: nothing
    // in the dynamics reads it back.
    double work = 0;
    double peakForce = 0;     // N
    Vec3   impulse{};         // N s delivered to A
    HullContact atPeak{};     // the geometry at the instant of peak force
    ContactLoad loadAtPeak{};

    // Add one step. `dt` is the step the load was applied over.
    void accumulate(const HullContact& contact, const ContactLoad& load,
                    const ContactBody& a, const ContactBody& b, double dt);
};

// --- Ships --------------------------------------------------------------------

// The rigid body `ship` presents to the contact solver: its own mass properties,
// carried into world axes, with the velocity referred to the centre of gravity
// rather than to the body origin. `Ship::state.velocity` is the *origin's*, and
// using it as the cog's is the same class of error as reading `state.velocity.x`
// as a ship's speed.
ContactBody contactBodyOf(const Ship& ship);

// Detect contact between two ships and add the resulting force and moment to both.
// Call once per step, *before* stepping either ship; `Ship::step()` consumes and
// clears the accumulators. Returns the geometry, whether or not it was touching.
HullContact applyContact(Ship& a, Ship& b, const ContactMaterial& material, double dt,
                         ContactHistory* history = nullptr,
                         const ContactParams& params = {});

}  // namespace sim
