// SPDX-License-Identifier: MIT
//
// Compile-time type reflection.
//
// docs/01-architecture.md §2 wants one description of a type driving four
// consumers: serialisation, network replication, editor property panels and the
// save format. This is that description.
//
// It is macro-based rather than generated by a build-time parser. The parser is
// still the right end state -- annotating a header beats repeating field names --
// but it needs libclang, a build step, and a way to keep generated output in
// sync, none of which earn their cost before there is anything consuming the
// tables. The macros produce exactly the structures a generator would emit, so
// swapping the front end later changes no consumer.
#pragma once

#include <cstddef>
#include <cstdint>
#include <string_view>
#include <type_traits>

namespace core {

// FNV-1a over the type's name. Unlike a registration-order index this is a
// property of the type itself, so it is identical across builds, machines and
// link orders -- which is what makes saved data and replicated state portable.
constexpr std::uint64_t stableHash(std::string_view text) {
    std::uint64_t hash = 1469598103934665603ull;
    for (char c : text) {
        hash ^= static_cast<std::uint64_t>(static_cast<unsigned char>(c));
        hash *= 1099511628211ull;
    }
    return hash;
}

enum class TypeKind : std::uint8_t {
    Bool,
    Int8, Int16, Int32, Int64,
    UInt8, UInt16, UInt32, UInt64,
    Float32, Float64,
    Struct,
};

// Byte width of a scalar kind, as it appears on the wire. Struct has no fixed
// width and reports zero.
constexpr std::uint32_t kindByteWidth(TypeKind kind) {
    switch (kind) {
        case TypeKind::Bool:
        case TypeKind::Int8:
        case TypeKind::UInt8: return 1;
        case TypeKind::Int16:
        case TypeKind::UInt16: return 2;
        case TypeKind::Int32:
        case TypeKind::UInt32:
        case TypeKind::Float32: return 4;
        case TypeKind::Int64:
        case TypeKind::UInt64:
        case TypeKind::Float64: return 8;
        case TypeKind::Struct: return 0;
    }
    return 0;
}

template <typename T>
struct Reflect {
    static constexpr bool kReflected = false;
};

template <typename T>
concept Reflected = Reflect<T>::kReflected;

template <typename T>
constexpr TypeKind typeKindOf() {
    if constexpr (std::is_same_v<T, bool>) return TypeKind::Bool;
    else if constexpr (std::is_same_v<T, float>) return TypeKind::Float32;
    else if constexpr (std::is_same_v<T, double>) return TypeKind::Float64;
    else if constexpr (std::is_integral_v<T> && std::is_signed_v<T>) {
        if constexpr (sizeof(T) == 1) return TypeKind::Int8;
        else if constexpr (sizeof(T) == 2) return TypeKind::Int16;
        else if constexpr (sizeof(T) == 4) return TypeKind::Int32;
        else return TypeKind::Int64;
    } else if constexpr (std::is_integral_v<T>) {
        if constexpr (sizeof(T) == 1) return TypeKind::UInt8;
        else if constexpr (sizeof(T) == 2) return TypeKind::UInt16;
        else if constexpr (sizeof(T) == 4) return TypeKind::UInt32;
        else return TypeKind::UInt64;
    } else {
        return TypeKind::Struct;
    }
}

struct TypeInfo;

struct FieldInfo {
    const char*     name = "";
    std::uint64_t   nameHash = 0;
    TypeKind        kind = TypeKind::Struct;
    std::uint32_t   offset = 0;
    std::uint32_t   elementSize = 0;  // in memory, per element
    std::uint32_t   count = 1;        // array extent; 1 for a scalar
    const TypeInfo* nested = nullptr; // set when kind == Struct
};

struct TypeInfo {
    const char*      name = "";
    std::uint64_t    stableId = 0;
    std::uint32_t    size = 0;
    std::uint32_t    alignment = 0;
    const FieldInfo* fields = nullptr;
    std::uint32_t    fieldCount = 0;

    const FieldInfo* findField(std::uint64_t hash) const {
        for (std::uint32_t i = 0; i < fieldCount; ++i)
            if (fields[i].nameHash == hash) return &fields[i];
        return nullptr;
    }
};

template <typename T>
FieldInfo makeFieldInfo(const char* name, std::size_t offset) {
    using Element = std::remove_all_extents_t<T>;
    FieldInfo field;
    field.name = name;
    field.nameHash = stableHash(name);
    field.kind = typeKindOf<Element>();
    field.offset = static_cast<std::uint32_t>(offset);
    field.elementSize = static_cast<std::uint32_t>(sizeof(Element));
    field.count = static_cast<std::uint32_t>(sizeof(T) / sizeof(Element));
    if constexpr (Reflected<Element>) field.nested = &Reflect<Element>::info();
    return field;
}

inline TypeInfo makeTypeInfo(const char* name, std::size_t size, std::size_t alignment,
                             const FieldInfo* fields, std::size_t fieldCount) {
    TypeInfo type;
    type.name = name;
    type.stableId = stableHash(name);
    type.size = static_cast<std::uint32_t>(size);
    type.alignment = static_cast<std::uint32_t>(alignment);
    type.fields = fields;
    type.fieldCount = static_cast<std::uint32_t>(fieldCount);
    return type;
}

template <typename T>
const TypeInfo& typeInfo() {
    return Reflect<T>::info();
}

}  // namespace core

// Declare reflection for a type at global scope:
//
//   SHIPSIM_REFLECT_BEGIN(Position)
//       SHIPSIM_FIELD(x)
//       SHIPSIM_FIELD(y)
//   SHIPSIM_REFLECT_END(Position)
//
// The name passed here is what the stable id hashes, so renaming a type breaks
// compatibility with data already written. That is deliberate: a silent rename
// that kept the id would deserialise the wrong fields into it.
#define SHIPSIM_REFLECT_BEGIN(TypeName)                                           \
    namespace core {                                                              \
    template <>                                                                   \
    struct Reflect<TypeName> {                                                    \
        using Self = TypeName;                                                    \
        static constexpr bool kReflected = true;                                  \
        static const ::core::TypeInfo& info() {                                   \
            static const ::core::FieldInfo fields[] = {

#define SHIPSIM_FIELD(member)                                                     \
                ::core::makeFieldInfo<decltype(Self::member)>(#member,            \
                                                              offsetof(Self, member)),

#define SHIPSIM_REFLECT_END(TypeName)                                             \
            };                                                                    \
            static const ::core::TypeInfo type = ::core::makeTypeInfo(            \
                #TypeName, sizeof(Self), alignof(Self), fields,                   \
                sizeof(fields) / sizeof(fields[0]));                              \
            return type;                                                          \
        }                                                                         \
    };                                                                            \
    }
